### ISSUE TITLE
Java lang index out of bounds exception

### ISSUE THREAD

**Issue by huellasiscool** [SneakySpook/Tickompiler#10]
Every time I try and pack a thing that I compiled it gives me this exact error, I've tried changing up the tickflow, I've tried changing the engine and tempo, and even bringing the tickflow and tempo to the original state.

But still gives me the exact error (Also I worked on the tickflow and tempo several times before and it didn't give me an issue but when I try and pack it now it just doesn't work.) 

Also, I've seen other people come in contact with the same error but they were working on a compressed code.bin however, mine is an uncompressed 4MB one.
![image](https://user-images.githubusercontent.com/85096210/125858944-97affef2-7fd9-4560-842d-0b4886f5803d.png)

Here's what happens when I try and pack the file.

`p mod base.bin
Packing 10000B7.tempo...
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (rhmodding.tickompiler.cli.PackCommand@66a3ffec): java.lang.IndexOutOfBoundsException
        at picocli.CommandLine.execute(CommandLine.java:1056)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1223)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1131)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1414)
        at rhmodding.tickompiler.Tickompiler.createAndParseCommandLine(Tickompiler.kt:16)
        at rhmodding.tickompiler.cli.DaemonCommand.run(DaemonCommand.kt:35)
        at picocli.CommandLine.execute(CommandLine.java:1048)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1223)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1131)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1414)
        at rhmodding.tickompiler.Tickompiler.createAndParseCommandLine(Tickompiler.kt:16)
        at rhmodding.tickompiler.Tickompiler.main(Tickompiler.kt:24)
Caused by: java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Unknown Source)
        at java.nio.HeapByteBuffer.getInt(Unknown Source)
        at rhmodding.tickompiler.gameputter.GamePutter.putTempo(GamePutter.kt:76)
        at rhmodding.tickompiler.cli.PackCommand.run(PackCommand.kt:102)
        at picocli.CommandLine.execute(CommandLine.java:1048)
        ... 15 more`

**Comment by huellasiscool** [comment]
if you want more info, go here
https://ptb.discord.com/channels/277545487375007744/438475764493582356/865300962863611904

**Comment by patataofcourse** [comment]
I don't think anyone's been able to recreate this since, so I'll chalk it up to a faulty setup for now. If anyone has any more issues feel free to open another issue or post another comment in this one.
