### ISSUE TITLE
Compiling Tickflow fails when building from source

### ISSUE THREAD

**Issue by flvinny** [SneakySpook/Tickompiler#11]
Building Tickompiler from source on the current version of IntelliJ breaks the Tickflow compiler. Everything else appears to work as it should. (Extracting, packing, decompiling...)
```
Compiling 1 file(s) 
Compiling code\newEndless.tickflow
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (rhmodding.tickompiler.cli.CompileCommand@19bb089b): java.lang.RuntimeException: Error creating extended parser class: An ACTION or Var initializer in rule method 'AliasAssignment' contains illegal writes to a local variable or parameter
	at picocli.CommandLine.executeUserObject(CommandLine.java:1948)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2550)
	at rhmodding.tickompiler.Tickompiler.createAndParseCommandLine(Tickompiler.kt:16)
	at rhmodding.tickompiler.Tickompiler.main(Tickompiler.kt:24)
Caused by: java.lang.RuntimeException: Error creating extended parser class: An ACTION or Var initializer in rule method 'AliasAssignment' contains illegal writes to a local variable or parameter
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at rhmodding.tickompiler.compiler.Compiler.compile(Compiler.kt:128)
	at rhmodding.tickompiler.cli.CompileCommand$run$1$1.invokeSuspend(CompileCommand.kt:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: org.parboiled.errors.GrammarException: An ACTION or Var initializer in rule method 'AliasAssignment' contains illegal writes to a local variable or parameter
	at org.parboiled.support.Checks.ensure(Checks.java:37)
	at org.parboiled.transform.InstructionGroupCreator.verify(InstructionGroupCreator.java:135)
	at org.parboiled.transform.InstructionGroupCreator.process(InstructionGroupCreator.java:58)
	at org.parboiled.transform.ParserTransformer.runMethodTransformers(ParserTransformer.java:62)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:45)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:39)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
	... 8 more

Process finished with exit code 1
```

https://github.com/rhmodding/Tickompiler/blob/bb28483a47bca8700f6402a3f1fe3e88993ffafb/src/main/kotlin/rhmodding/tickompiler/compiler/Parboiled.kt#L165-L169

**Comment by chrislo27** [comment]
Issue was caused by a new Parboiled library dependency version. It has been rolled back to 1.2.0 as of commit c2e3fb2260d76d63e8b205e1ded5adb3dbc8f2a0.

**Comment by chrislo27** [comment]
There are bytecode changes between Kotlin 1.3 and 1.5. (Technically also Kotlin 1.4.) Below are JVM bytecode-to-Java decompilations.

I can confirm that compiling with Kotlin 1.3 works but Kotlin 1.5 doesn't for compiling `agbBatter.tickflow` from the standard decompilation.

Kotlin 1.3:
```java
   @NotNull
   public Rule AliasAssignment() {
      Rule var10002 = this.Optional(this.Whitespace());
      Object[] var10003 = new Object[]{this.VariableIdentifier(), this.Optional(this.Whitespace()), this.Expression(), null};
      AliasAssignNode var10007 = new AliasAssignNode;
      Position var10009 = this.position();
      Intrinsics.checkExpressionValueIsNotNull(var10009, "position()");
      Object var10010 = this.pop(1);
      if (var10010 == null) {
         throw new TypeCastException("null cannot be cast to non-null type kotlin.String");
      } else {
         String var1 = (String)var10010;
         Object var10011 = this.pop();
         if (var10011 == null) {
            throw new TypeCastException("null cannot be cast to non-null type rhmodding.tickompiler.compiler.ExpressionNode");
         } else {
            var10007.<init>(var10009, var1, (ExpressionNode)var10011);
            var10003[3] = this.push(var10007);
            Rule var10000 = this.Sequence("#alias", var10002, var10003);
            Intrinsics.checkExpressionValueIsNotNull(var10000, "Sequence(\"#alias\", Optio…op() as ExpressionNode)))");
            return var10000;
         }
      }
   }
```

Kotlin 1.5:
```java
   @NotNull
   public Rule AliasAssignment() {
      Rule var10002 = this.Optional(this.Whitespace());
      Object[] var10003 = new Object[]{this.VariableIdentifier(), this.Optional(this.Whitespace()), this.Expression(), null};
      AliasAssignNode var10007 = new AliasAssignNode;
      Position var10009 = this.position();
      Intrinsics.checkNotNullExpressionValue(var10009, "position()");
      Object var10010 = this.pop(1);
      if (var10010 == null) {
         throw new NullPointerException("null cannot be cast to non-null type kotlin.String");
      } else {
         String var1 = (String)var10010;
         Object var10011 = this.pop();
         if (var10011 == null) {
            throw new NullPointerException("null cannot be cast to non-null type rhmodding.tickompiler.compiler.ExpressionNode");
         } else {
            var10007.<init>(var10009, var1, (ExpressionNode)var10011);
            var10003[3] = this.push(var10007);
            Rule var10000 = this.Sequence("#alias", var10002, var10003);
            Intrinsics.checkNotNullExpressionValue(var10000, "Sequence(\"#alias\", Optio…op() as ExpressionNode)))");
            return var10000;
         }
      }
   }
```
