### ISSUE TITLE
Access denied while compiling a tfobj file

### ISSUE THREAD

**Issue by BobTheNerd10** [SneakySpook/Tickompiler#7]
I typed "c -o=tempo tickflow bin" into tickompiler
Tempo contains a singular tempo file
Tickflow contains a singular tickflow file
Bin contains nothing

Compiling 1 file(s) with 1 tempo files
Compiling tickflow\remix09.tickflow
Compiled tickflow\remix09.tickflow -> 1603.2243 ms

+========================+
| COMPILATION SUCCESSFUL |
+========================+
All 1 targets were compiled successfully. (Took 2331.9089 ms)
Building object file bin...
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (rhmodding.tickompiler.cli.CompileCommand@6e06451e): java.io.FileNotFoundException: bin (Access is denied)
        at picocli.CommandLine.execute(CommandLine.java:1056)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1223)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1131)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1414)
        at rhmodding.tickompiler.Tickompiler.createAndParseCommandLine(Tickompiler.kt:16)
        at rhmodding.tickompiler.cli.DaemonCommand.run(DaemonCommand.kt:35)
        at picocli.CommandLine.execute(CommandLine.java:1048)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1223)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1131)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1414)
        at rhmodding.tickompiler.Tickompiler.createAndParseCommandLine(Tickompiler.kt:16)
        at rhmodding.tickompiler.Tickompiler.main(Tickompiler.kt:24)
Caused by: java.io.FileNotFoundException: bin (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at rhmodding.tickompiler.objectify.ObjectifierKt.objectify(Objectifier.kt:15)
        at rhmodding.tickompiler.cli.CompileCommand$run$2.invokeSuspend(CompileCommand.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at rhmodding.tickompiler.cli.CompileCommand.run(CompileCommand.kt:105)
        at picocli.CommandLine.execute(CommandLine.java:1048)
        ... 15 more

**Comment by chrislo27** [comment]
In your input, is `bin` a folder or a file? For `--objectify` (`-o`) to work, the output *file* must be specified (e.g.: `test.tfobj`) and not the folder. If the file you specify is inside multiple folders, all of the folders leading up to the file must exist first (e.g.: if you specified `bin1/bin2/test.tfobj`, then you should have a folder bin2 inside a folder bin1).

**Comment by Jornker** [comment]
Got the same error
p pack base.bin
Packing 100006A.tempo...
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (rhmodding.tickompiler.cli.PackCommand@5c7fa833): java.lang.NumberFormatException: For input string: "97.0"
        at picocli.CommandLine.execute(CommandLine.java:1056)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1223)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1131)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1414)
        at rhmodding.tickompiler.Tickompiler.createAndParseCommandLine(Tickompiler.kt:16)
        at rhmodding.tickompiler.cli.DaemonCommand.run(DaemonCommand.kt:35)
        at picocli.CommandLine.execute(CommandLine.java:1048)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1223)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1131)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1414)
        at rhmodding.tickompiler.Tickompiler.createAndParseCommandLine(Tickompiler.kt:16)
        at rhmodding.tickompiler.Tickompiler.main(Tickompiler.kt:24)
Caused by: java.lang.NumberFormatException: For input string: "97.0"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at rhmodding.tickompiler.gameputter.GamePutter.putTempo(GamePutter.kt:60)
        at rhmodding.tickompiler.cli.PackCommand.run(PackCommand.kt:102)
        at picocli.CommandLine.execute(CommandLine.java:1048)
        ... 15 more
Just tried compiling a single tempo file
